apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tgis-llm-demo
patchesJSON6902:
  - target:
      group: operators.coreos.com
      version: v1
      kind: OperatorGroup
      name: redis
    patch: |-
      - op: replace
        path: /spec/targetNamespaces/0
        value: tgis-llm-demo
resources:
  - ../../base/operators.coreos.com/operatorgroups/redis
  - ../../base/operators.coreos.com/subscriptions/redis
  - ../../base/redisenterprises
  - ../../base/redisenterprisedatabases
  - ../../base/deployments
  - ../../base/services
  - ../../base/configmaps
  - ../../base/persistentvolumeclaims
  - ../../base/routes
  - ../../base/jobs
  - namespaces
